spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    password:
    hikari:
      connection-timeout: 3000
      auto-commit: false
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true